language: android
env:
  global:
  - secure: Q2NXQrC5iHGDj7xpQe3s/aZ58mwqea3k7XGGmK4Fobvuu0HpJvYJU5bsUMLIzYyXq4kkmtbRa5abLOYLcvn/vXrAWk/2xAm/hhvVMaJn0xnKjj7kH1tr4CeMb4LWwq4gKB0RIk+Mh5EqGqDWMDPz0dMKfuqzw8Q2zmo21v6yDuj7M1gXY/Dvtjip2OFiZReMU/0TAvToSIqwZzR2OQ4GMJHzJMOaGmNCIUrX7r/HMGBMLD1Feg08sAbGqaKCmwr2/uYSM1zDJnqza8Jl+xvqAVAP+3Pcu5klKmdgr9yt6mbjJrRMng7EdOLAuirwXQ8Y2wqrfAxw0ya8p4TzfVeem7ZqszxaigbHYsADQ5Nv8liCZ0zSFoCKfNLb09AVIMqrimuMdY8VeJJdUCdb5eD22DACAQbnFmGEKJSPaAdS4vx366ul3hbTqbBt03kGxOh1BC2iAsNEeeB/ORrR87D+PA5Q7rC/KERblUiL0wcBC/HnYhtmcMkwJqxPLp1rGsy6yXXvI4h7JB41xk3eKZMP7I+c08pvjp9cfwnoSZqkXPhQyofajhrJ0uCZ/xUz5pnJA+aYHrRRqLmaHmbDYTFJet/2OU+xWqCsEfEVwZFJz5z8lYpu03F3Jk4t2HUOQLvPGjn/MFlLes4FCsPdsxJu8pwDZMMzQzQDRGkFxEJbz0c=
  - secure: aHnaDlLU7kAoL768Lm2YTHyPWNzThFEuPS+C1amFX4vTjQ8+Ux2lCG1BrsraJNevgnmWzCyL8f9lry5D8zfpxaZeonC8aylFmmw3+wy0y/7hjkbDDGaxPypObx9iB1Vwr8tnwCoexJ7G9V6fGz09G1+X4W9VU5so5AHtqBnopFLv9GTwQOtKSWQWvw85P85wV2lnGFdxysbJR0sNLl/j8czaqCEXHIYErhexLoUEmIBBbmtrhOqfhTiY4ek3uoopS+QXX+4F5IOYvqjKftELrzhc/uQPnuR4+/uhATeUPT0PrGURutqr+IgM0TJoL6pZIausVndcqGpIlm9PdBouSYxi1/d/I23W4PZ0XFN+RgLZkPOI0AiQBbKC3pF8M7iBc+o6roM4CDZ+/WV3mmWXJzsi1O6otmmPx2CnjDKaadiqkdVf6wtbWrrJgyWEfGkg3I60xizc8n+Wjjrd0Wj9lHgVLd5UZo5dghys/8+4iWWNw2mlBp4+1kCS9Y2nwj/yKxgepHjzommonvccqgJn+6mplUdDKyCmHP3kk95ZhFkdgOG3rGSxr+qb5QnYZW+a91VEneTpJ/M8haL+aGc3qhm+pLihxxqb8top/YGNoPMetHgYnwHbiv93U/mMFY3fWJryijRJoP2WTopb46fMDIHcbSmINRIAVtuxHBfDVKo=
install:
- npm install
- sed -i "s/23\.0\.1/25.0.0/g" node_modules/react-native-localization/android/build.gradle
- sed -i "s/23\.0\.1/25.0.0/g" node_modules/react-native-beacons-android/android/build.gradle
- sed -i "s/23\.0\.1/25.0.0/g" node_modules/react-native-fcm/android/build.gradle
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
script:
- npm run test
- cd android && ./gradlew assembleRelease
before_install:
- nvm install 6
- node --version
- openssl aes-256-cbc -K $encrypted_3aca4c1762c3_key -iv $encrypted_3aca4c1762c3_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_deploy:
- rvm 1.9.3 do gem install octokit -v 4.3.0
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk STOP2 -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
- "${ANDROID_HOME}/build-tools/25.0.0/zipalign 4 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk $TRAVIS_BUILD_DIR/android/STOP2.apk"
deploy:
  provider: releases
  api_key:
    secure: VjuBp+IKx99ZOjp3/7+gBoDzKHWCYE7x9l70+2Q7X253BmMaQfAThP6aBDeXCBbsmTZNpjbYD1Vtx0JXcnmLZTwFevuLp5AeGmBGCecqi927mebMyoeRj49ZtS2FmoueDVhbRRasSgviVocsLXSa5BQKJ3J5CfcbCBbWj1cdylgSBA9a57UxHToYr0oFTbAoa3z7eOGfZhq3Yf00osMRm4zhlK18EEiC9Y6ibpppGRY6V9umzTnE3h0pV9IHvIf7Txr0aSy5WZSc35eYqVPtHbSZnp/j3gSIRgf3nxMWH1RCCv8g4GMQWoko9DGzLhlQpfUyHEvk4CzE5pa3LrfnKNVDnOPc8SiBmGUXtFdRs+4amH7wNAdqNrdQYOTgZbteYjRSDOYZWqT2+g9iuDb/nW/nQvfxLM2NEMiAnnvgsoORB1W2AjaCBCo4ytYIDM8PmdIqoGwCtDtz47GM/gmwbaCY2/62O94Vxd+35kylM9Wwa8VBIbXp20rfuDj3SoxBCwkGRUQyEZe7oMyN0tYi7QV+nd3aG5DqFyLnduWzqvwhLPzObNCoOe5v8aQzeryJwXePb5KUh3r/bFy+0H6LhEEYxtdwYW9DZjEnRPIIU5oeM6cf++Z4z9JVfnQTdQQ1V18b8SHoPu1EswrTXlO3BewgzvqnfUnz3JhsNjFMPKs=
  file: "$TRAVIS_BUILD_DIR/android/STOP2.apk"
  on:
    repo: STOP2/stop2.0-traveller-client
    tags: true
notifications:
  slack:
    secure: FC6pCe4YbbDVGgGNcHxp3tTe8i4rD+jT/+9ZuNF6vS/7cSkzfABGoEIlJMtPgUNl0B8N8MHvKFslMazgboLjnzdjLnNxsqnhUY17Mnpx4uyUqjnppel+FsbNkty6pRxNibwK2N131YjsPhpnLnDOv50S7H0MH+q7dk36sBm2l55Xltqkt5B3LdLkT0QpplbgiR8GoK6uo8au/OBqC8O1AyQojFSezVH2ceh/NjHzeEhPGMwT1hnHricq1VCxU8ORB7YITiZ7KDgkv46dp4YME31Rrqh94oYY4OdunRDkTpWuZpe9VXDx4YqLM3x8Ew3DsN9R94YmHW3JJr4hZK1pwqXgZ9Lih6tqW0Qepf8fw4ciSEEXlr1iQsSFeJsALOg3e1X9LichY+4GoZFs35RD2TK1LSxmpyje2lWIuRA+jgv+bGuWJay4APJ/gDYtiSapq32dgJ13h/bMG6iwHCA+wWdkpMwfr45hEAr2oW9z4FKgb58OXfx4IcbFEXvHPR+4KB28Yo4KHPvOwa0HlZXL65tt3mkUhaJ5nOnTLhdbkFDp5L8JXT8ZKk8QO0gs6rTRyLjYvQVAWR+dxIYEWldnlpgOYGzdilj3VA+GOk/UJaaLHkjCq1mNzyY1YuVKpQzjB0MW3gyO7Yv9TXP8Ov57mOdsylvlIYu7uEFMpmC3GNM=
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - node_modules
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
