language: android

sudo: true

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-23.0.3
    - android-23

    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-23

jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g n
  - sudo -E env "PATH=$PATH" n stable
  - npm install -g react-native-cli
  - npm install
  - rvm install 2.0.0
  - gem install calabash-android

before_script:
  - react-native start &
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - cd android
  - ./gradlew clean assembleDebug -PdisablePreDex --continue --stacktrace

script:
  - calabash-android resign app/build/outputs/apk/app-debug.apk
  - calabash-android run app/build/outputs/apk/app-debug.apk
