language: node_js
node_js:
- '4'
script:
- npm run test
before_install:
 - gem install coveralls-lcov
notifications:
  slack:
    secure: FC6pCe4YbbDVGgGNcHxp3tTe8i4rD+jT/+9ZuNF6vS/7cSkzfABGoEIlJMtPgUNl0B8N8MHvKFslMazgboLjnzdjLnNxsqnhUY17Mnpx4uyUqjnppel+FsbNkty6pRxNibwK2N131YjsPhpnLnDOv50S7H0MH+q7dk36sBm2l55Xltqkt5B3LdLkT0QpplbgiR8GoK6uo8au/OBqC8O1AyQojFSezVH2ceh/NjHzeEhPGMwT1hnHricq1VCxU8ORB7YITiZ7KDgkv46dp4YME31Rrqh94oYY4OdunRDkTpWuZpe9VXDx4YqLM3x8Ew3DsN9R94YmHW3JJr4hZK1pwqXgZ9Lih6tqW0Qepf8fw4ciSEEXlr1iQsSFeJsALOg3e1X9LichY+4GoZFs35RD2TK1LSxmpyje2lWIuRA+jgv+bGuWJay4APJ/gDYtiSapq32dgJ13h/bMG6iwHCA+wWdkpMwfr45hEAr2oW9z4FKgb58OXfx4IcbFEXvHPR+4KB28Yo4KHPvOwa0HlZXL65tt3mkUhaJ5nOnTLhdbkFDp5L8JXT8ZKk8QO0gs6rTRyLjYvQVAWR+dxIYEWldnlpgOYGzdilj3VA+GOk/UJaaLHkjCq1mNzyY1YuVKpQzjB0MW3gyO7Yv9TXP8Ov57mOdsylvlIYu7uEFMpmC3GNM=
after_success:
- coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.npm
    - node_modules
