language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-23.0.3
    - android-23

    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-23

jdk: oraclejdk8
rvm: 2.2

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/
    - node_modules

before_install:
  - npm install -g npm@latest
  - npm install
  - rvm install 2.0.0
  - gem install calabash-android

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - cd android
  - ./gradlew clean assembleDebug -PdisablePreDex --continue --stacktrace
