# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stop2TravellerClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Stop2TravellerClient
  pod 'Firebase/Messaging'

  target 'Stop2TravellerClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
